version: '3.9'

services:
  expense:
    container_name: nest-backend
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
